
name: newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} #!!
        password: ${{ secrets.DOCKERHUB_TOKEN }} #!!

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: './Dockerfile'
          push: true
          tags: neskred/dalle:latest
    container: alphine:latest
    steps:
    - name: "Run Docker image api"
      run: "echo 'hello world'"
    # - uses: actions/checkout@master
    # - uses: matt-ball/newman-action@master
    #   with:
    #     collection: DockerDall.postman_collection.json