
name: Intergra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run Docker image api"
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and run Docker image
      working-directory: ./DallApi/DallApi
      run: |
        ls
        docker build -t my-image .
        docker run -t -p 80:80 my-image
        docker ps 
    # - uses: actions/checkout@master
    # - uses: matt-ball/newman-action@master
    #   with:
    #     collection: DockerDall.postman_collection.json