
name: Intergration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} #!!
        password: ${{ secrets.DOCKERHUB_TOKEN }} #!!
    - name: build and run sql server
      working-directory: ./
      run: |
        docker 
        docker run -p 1433:1433 -d --name database neskred/dalle:database_empty
    - name: Build and run Docker image
      working-directory: ./DallApi/DallApi
      run: |
        ls
        docker build -t my-image .
        docker run -d -p 80:80 -e DATABASE_CONECTION="Server=172.1.0.1,1433;Database=master;User Id=sa;Password=Test1234;" --name api my-image
    - name: network create
      working-directory: ./DallApi/DallApi
      run: |
        docker exec api env
        docker container ls
        docker network create -d bridge my-bridge-network
        docker network connect my-bridge-network api
        docker network connect my-bridge-network --ip 172.1.0.1 database
        docker network inspect my-bridge-network



    - uses: actions/checkout@master
    - uses: matt-ball/newman-action@master
      with:
        collection: DockerDall.postman_collection.json

    - name: Dump redis logs
      uses: jwalton/gh-docker-logs@v2
      with:
        images: 'my-image'
        # Only show last 100 lines of each
        tail: '100'