
name: Intergra

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run Docker image api"
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: actions/setup-docker@v1
    - name: Build and run Docker image
      run: |
        docker build -t my-image .
        docker run --rm -it my-image
        docker ps 
    # - uses: actions/checkout@master
    # - uses: matt-ball/newman-action@master
    #   with:
    #     collection: DockerDall.postman_collection.json